includes/addons/custom-fields/class-display.php
includes/addons/custom-fields/class-save.php
includes/class-product-sync.php

Fixes issues related to e-commerce products synchronization ( see #93 ). This is still not perfect as there are at least two issue but they are minor and should not cause any problem in our case. The known issues are documented in the class description.

Fix Product Sync Issues - closes #93

---

class-awesome-support.php
includes/addons/custom-fields/class-custom-fields.php

This is a nice option to filter custom fields. We use it for example on the submit ticket page to display only products which user has purchased instead of the entire product list.

Added filter to add_field function to allow users to modify fields

---

includes/addons/file-uploader/class-file-uploader.php

I wanted to change how the filetype is displayed in the help paragraph under the uploader on the front end and couldn't find an appropriate filter. This adds a filter to do this.

Added filter for filetype display

---

composer.json

@julien731 I added this to my fork, so I could you composer to install WPAS.
The process is not straightforward, because I have to `composer update` twice, since you require your own `vendor`, even if I have Titan and WP Session already in my project - but these lines still have to be in your `composer.json`.
Thank you!
P.S. You might want to add other fields there, such as `author`, etc.

composer.json name,description and type

---

includes/custom-fields/class-custom-fields.php

Changed the status_filter function to return false if one of the conditions are met. The previous version only echoed an empty string. This made the status dropdown visible on all custom field list tables.

status_filter function

---

includes/admin/class-admin.php

Hey. This is my first ever contribution to a project via GIT - I hope it's ok, let me know if not as I'd like to become involved.
Thanks

Fixed wrong settings link on module page

---

includes/class-member-query.php
includes/functions-user.php

Julien, I was seeing errors in PHP log regarding use of member on nonobject. This commit resolves that problem.

Check $post is valid before calling is_user_logged_in() in wpas_can_view_ticket()

---

includes/admin/functions-post.php

- Code styling
- Strengthen the var sanitization
- Prefix functions
- Use `WPAS_Session` class instead of PHP sessions

Code refactor

---

includes/admin/class-admin-tickets-list.php

Code cleanup, documentation, removal of debug code. Fixed custom field sorting.

Ticket List: Fix custom field sorting

---

includes/custom-fields/functions-custom-fields.php
includes/functions-templating.php
uninstall.php

add: Ticket ID to Ticket Title on frontend tickets list.
fix: Delete file attachments for posts on uninstall. 
fix: Change hook name for Department taxonomy labels from wpas_product_taxonomy_labels to wpas_department_taxonomy_labels. Core AS does not use this hook. Any addon that does will need to be updated with the new hook name.

Minor AS Core Bug Fixes

---

includes/admin/functions-tools.php
includes/admin/metaboxes/time-tracking-statistics.php
includes/class-product-sync.php
includes/custom-fields/functions-custom-fields.php
includes/file-uploader/class-file-uploader.php
includes/functions-templating.php

Time tracking field values are now saved as an integer instead of a string in 'hh:mm:ss' format.
Seconds granularity is no longer supported.
Time tracking field values are displayed and input in 'hh:mm' format.
Addons that update time tracking fields directly should save and read as integer values representing the number of minutes.

Time Tracking Fields

---

includes/admin/functions-tools.php

Fixed product sync issue, by making sync update product terms instead of deleting them (codup).

Fixed product sync issue

---

includes/functions-user.php

when $args is empty, set it to array()

to void the input is ''

---

assets/admin/js/admin-users.js
includes/functions-user.php

Searching via ajax (drop-down suggestions) is confusing when thousands of users exist

---

includes/admin/functions-user-profile.php
includes/admin/metaboxes/replies-published.php
includes/admin/metaboxes/stakeholders.php
includes/admin/metaboxes/user-profile.php
includes/class-email-notifications.php

Adding checks on variable usage

---

includes/class-email-notifications.php

Bug fix on email content where quotes are not escaped

Email: Strip slashes issues

---

includes/admin/class-admin-tickets-list.php

This pull request adds support based on the options selected in the Advanced tab in Settings for searching for a ticket based on is help desk ID for imported tickets.

Search for ticket by help desk id

---

includes/scripts.php

Bug fix in which GDPR popup is visible by default in non WPAS pages and even non-logged users

Hotfix: Fix bug for GDPR popup

---

awesome-support.php
includes/admin/settings/settings-registration.php
includes/class-user-email-notification.php
includes/functions-user.php
themes/default/registration.php

New Moderated Registration option is added where we allow the registration but the user has to be approved by an admin

Moderated Registration

---

assets/admin/js/admin-ajax-upload.js
includes/file-uploader/class-file-uploader.php

Added timeout parameter to Dropzone.js which is equal to php max_execution_time value

 Added Dropzone timeout parameter

---

assets/admin/less/admin.less
includes/admin/class-admin-tickets-list.php

Add new search controls like, search by subject, opening post, replies or private notes

Ticket Listing Page : Add search controls

---

assets/admin/js/admin.js
assets/public/js/component_ticket.js
includes/admin/settings/settings-style.php
includes/scripts.php

This pull requests adds the ability to configure whether or not the autolinker is turned on or off. I turn off autolinker script inclusion based on the `use_autolinker` option. And then in the javascript, I checked to see if the Autolinker object is defined.

Added ability to configure autolinker.

---

assets/admin/js/admin.js
assets/public/js/component_ticket.js
includes/scripts.php

This should fix the front-end issue described in #671

Improvements to use autolinker option for frontend. 

---

.gitignore
Gruntfile-poeditor.js
package-poeditor.json
readme.txt

* Version poeditor build scripts
* Version wordpress readme
* Ignore dist folder

Add poeditor build scripts and Wordpress readme

---

includes/admin/upgrade/class-upgrade.php
includes/admin/upgrade/functions-upgrade.php

Hey Ahmed,
This Pull Request only has upgrade function for Awesome Support 6.0.0.
Thanks!

# Added upgrade function for Awesome Support 6.0.0

---

includes/admin/functions-misc.php
includes/functions-templating.php

Hey Ahmed,
This Pull Request will fix functional and visual bugs.
Thanks!

Fixed bugs and issues in Awesome Support 6.0.0

---

Gruntfile.js
awesome-support.php
includes/admin/class-admin-tickets-list.php
includes/class-email-notifications.php
themes/default/list.php
vendor-overrides/eric-mann-session-manager/ericmann/wp-session-manager/wp-session-manager.php

I have fixed couple of bugs in AS Core plug-in.
- WP query_vars empty index issue.
- Slash (/) issue in e-mail body.

Couple of fixes in the plug-in

---

includes/admin/metaboxes/message.php
includes/admin/metaboxes/replies-history.php
includes/admin/metaboxes/replies-published.php
includes/admin/views/print-ticket.php
includes/class-wpas-editor-ajax.php
includes/functions-post.php
themes/default/details.php
themes/default/partials/ticket-origin.php

Unslash content before display

---

includes/functions-post.php

Correctly handle errors during ticket open process

---

includes/admin/class-admin-tickets-list.php

Fix incorrect query key

---

awesome-support.php
includes/admin/upgrade/class-upgrade.php
includes/admin/upgrade/functions-upgrade.php
includes/admin/views/about-tab-change-log.php
package.json
readme.txt

Fix release 6.0.13
