Awesome-Support/Awesome-Support

includes/class-post-type.php, includes/functions-post.php, uninstall.php
Some fixes & improvements:
- Use wp_update_post instead of wpdb->query
See also: https://codex.wordpress.org/Function_Reference/wp_update_post
- Fixed: php notices on single ticket page
Need to use the ```init``` hook instead of ```after_setup_theme```, otherwise you'll get on the single ticket page php notices like following:
```Notice: Trying to get property of non-object in
/wp-includes/query.php on line 3516```
```Notice: Trying to get property of non-object in /wp-includes/query.php
on line 3521```
```Notice: Trying to get property of non-object in /wp-includes/query.php
on line 3530```
=> Bugfixes & improvements

includes/admin/class-admin-user.php
This commit fixes two small issues:
1. PHP Notice:  Undefined index: wpas_after_reply" when updating user profile on "Edit User" page:
PHP Notice:  Undefined index: wpas_after_reply in \wp\wp-content\plugins\awesome-support\includes\admin\class-admin-user.php on line 86
PHP Stack trace:
PHP   1. {main}() \wp\wp-admin\user-edit.php:0
PHP   2. do_action() \wp\wp-admin\user-edit.php:146
PHP   3. call_user_func_array() \wp\wp-includes\plugin.php:496
PHP   4. WPAS_User->save_user_custom_fields() \wp\wp-includes\plugin.php:496
2. Do not access superglobal $_POST Array directly
=> Fixed "PHP Notice:  Undefined index: wpas_after_reply"

includes/functions-templating.php
A simple solution is to apply `the_title` filter.
Optionally - can introduce a new `wpas_taxonomy_name` filter.
=> Do not output unflitered taxonomy name

includes/class-email-notifications.php
wpas_email_notifications_email isn't terribly useful as it - you can get the user, but you can't easily get other information about the ticket. Adding ticket_id as a 3rd argument will, without breaking any compatibility, allow easy modification of the email based on the ticket_id, or anything that can be found from the ticket_id.
=> Added ticket_id to wpas_email_notifications_email filter

includes/class-agent.php
Bug: When adding a ticket, if the open ticket count is zero, the new ticket count is 2 instead of 1 due to checking for empty (which could be a valid count of zero) instead of false.
So open_tickets counts 1 ticket, then ticket_plus increments it to 2.
=> Update ticket only when false, not zero

includes/file-uploader/class-file-uploader.php
Returns original filename when downloading attached files. This also fixes an issue where there was no file extension when downloading attached files, making binary files (like zip) hard to open (at least on Windows).
I added `Content-Disposition: inline` so that browser will try to open files (because of images, pdfs, etc.), but if you think it should be downloaded instead of opened then put `Content-Disposition: attachment` instead.
=> Use original filename for attachments

includes/file-uploader/class-file-uploader.php
Added email attachment support to Email Support addon. 
Email attachments are stored in wp-content/uploads/awesome-support/ticket_$ticket_id folder. The WPAS_File_Upload::delete_attachments deletes the attachment itself but leaves the attachment folder behind.
The ticket attachment folder needs to be removed as well as the .htaccess file in each folder. The new action wpas_attachments_after_delete allows this folder cleanup and will be handy for any addon needing to perform post attachment delete actions.
The Email Support addon will expect this action.
=> Add actions before/after attachment delete in WPAS_File_Upload

includes/admin/functions-tools.php, includes/admin/views/system-tools.php, includes/file-uploader/class-file-uploader.php, languages/awesome-support.pot
The File Upload class in core AS contains much of the logic needed to process uploads from form submissions or email attachments, but the logic was specific to the core AS Custom Field (uploads) and the My Tickets Open a Ticket.
**Example Usage:**
```
$attachments = array();
foreach ( $this->attachments as $attachment ) {
$attachments[] = array(
'filename' => $attachment['filename'],
'data'     => file_get_contents( trailingslashit( $attachment['basedir'] ) . $attachment['filename'] ),
);
}
do_action( 'wpas_process_ticket_attachments', $ticket_id, $attachments );
```
This PR provides **crucial** core support for WPAS-ES and WPAS-GF.
=> File Attachment support in core AS File Upload class

includes/file-uploader/class-file-uploader.php
Getting called in ES WP Cron events without a current user. Set current user to default assignee or user id 1.
=> fix: File Uploader class

includes/admin/class-admin-tickets-list.php, includes/custom-fields/class-custom-field.php
Core AS WPAS_Custom_Field::update_value() checked to see if a custom field contained a value by checking empty().  update_value() likely presumed custom field (postmeta) values would never be stored with NULL values. 
Added is_null() check on custom field value returned from postmeta.
=> Unable to Delete or Update existing AS Custom Fields containing NULL

.gitignore, includes/admin/class-admin-tickets-list.php, includes/class-product-sync.php, includes/custom-fields/class-custom-field.php
fix: posts_where() running on unrelated queries.
fix: Product sync get_terms() when only term IDs are specified.
fix: Agent column sorting in tickets list.
fix: Sort and filter by taxonomy caused duplicated SQL.
=> Multiple fixes

includes/admin/class-admin-tickets-list.php, includes/class-product-sync.php, includes/custom-fields/field-types/class-cf-checkbox.php, includes/custom-fields/field-types/class-cf-radio.php, themes/default/less/style.less
Strange issue that I thought was fixed once. I didn't fully understand the Product Sync logic. It appears that a Product taxonomy term is saved with name and slug as the post ID of the term. These name and slug values are set to the term's post_title and post_name properties.
The problem was in get_terms() where product terms were not being detected as synced WooCommerce products.
I think the problem was strictly aesthetic and no harm was done to any data.
=> fix: Product Sync name/slug displayed as term post ID

.travis.yml, composer.json, composer.lock
Please note I have locked the `ericmann/wp-session-manager` to commit `dev-master#c446c85909206345d875297d8691396e0ba624a3`. The `composer.json` was requesting any version `1.2.*` but the `composer.lock` was referencing this commit. 
I highly recommend upgrading to the latest verison of wp-session-manager as `dev-master` is known to be unstable stability with Composer
=> Fix PHPUnit on Travis for PHP7

awesome-support.php, includes/compatibility/wpml.php
- Translate page ids to correct language so that assets are loaded correctly in the frontend.
- First reported in WPML support:
https://wpml.org/forums/topic/awesome-support-plugin-missing-his-style-file-when-switch-to-another-language/
=> Add WPML compatibility

assets/admin/less/admin.less, includes/custom-fields/field-types/class-cf-radio.php
- changed "id" attribute to not use $option_id which may contain spaces, added a counter instead
- updated admin.less to display back-end radio labels as inline-block. The line will still break if the text is long, but I don't think that's a bad thing
- not sure why indentation looks weird
=> add clickable labels to radio options - attempt 2

assets/admin/css/wizard-notice.css
Force hide 'Setup Wizard' menu from appearing in WP menu
=> Wizard menu: Hide from admin menu

includes/admin/metaboxes/replies-published.php, includes/functions-user.php, themes/default/partials/ticket-origin.php
The user roles that would be returned from $user_data->roles where something like:
`{ [2] => 'Editor', [3] => 'Administrator' }`
I'm not sure if this is due to the user role editor plugin that we are using called 'User Role Editor'. Also the private notes plugin needs to be updated too:
class-private-note.php @ line 398:
`<?php echo wpas_get_user_nice_role( $user_data->roles ); ?>`
=> Fixed display of user role when array is not zero based.

assets/admin/js/admin-edit-ticket-content.js
I submitted a support request about this already, but here I believe is the fix. It copies the settings from the reply editor on the same page for initializing the edit ticket editor.
The problem is when having the productivity pack installed and having Use Teeny Editor as Disabled.
Then clicking on the Edit button for the ticket:
Shows this "minimial" editor instead of the full editor that is expected:
=> Productivity plugin editor settings not being applied to edit ticket editor

includes/class-email-notifications.php
I'm not sure if what I've done here is the best way to do it. But it seems that private notes of post type `ticket_note` are not supported in the WPAS_Email_Notification class. This won't actually send out e-mail notifications for private notes, but it will make the WPAS_Email_Notification class aware of them.
I have made two changes to the `wpas_email_notifications_notify_user` event: one that allows it to return multiple recipients and another that sends the `$post_id` or reply ID as that might be necessary for determining which users to notify.
=> Support for private notes in WPAS_Email_Notification

includes/functions-general.php
Currently, using WP-CLI on a site where Awesome-Support is activated causes PHP Undefined index notices for SERVER_NAME and SERVER_PORT.  This patch avoids querying the URL if the plugin is being loaded from WP-CLI, rather than the web.
=> Don't try to guess the URL if running from WP-CLI

includes/scripts.php
The JS asset 'wpas-admin-edit-ticket-content-script' was being enqueued on every Wordpress page. With this fix it'll be enqueued only on WPAS pages.
=> Enqueue 'wpas-admin-edit-ticket-content-script' only on plugin pages

includes/class-email-notifications.php
In some instances slashes were being removed from the email notifications we were receiving. If a user entered in a Windows file path in the reply to a ticket like so:
`c:\windows\desktop\x`
Then the email notification would come across as:
`c:windowsdesktop\x`
This changes moves the call to `stripcslashes` from being applied on the e-mail's body - to being applied on the email's template. So instead of it being applied after the email tags have been evaluated, it is applied to the template before the tags are evaluated.
=> Fix bug where slashes are stripped from e-mail message.

includes/file-uploader/class-file-uploader.php
Clean the output buffer before displaying attachments to prevent attachment corruption.
Fixes #727
=> Clean the output buffer

includes/admin/functions-tools.php, includes/class-product-sync.php
=> Corrects Product Sync Issues
